/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CandidaterRouteImport } from './routes/candidater'
import { Route as BilletterieRouteImport } from './routes/billetterie'
import { Route as BilletRouteImport } from './routes/billet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BilletterieGererRouteImport } from './routes/billetterie_.gerer'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin.categories.index'
import { Route as AdminBilletterieIndexRouteImport } from './routes/admin.billetterie.index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin.applications.index'
import { Route as AdminCategoriesSlugRouteImport } from './routes/admin.categories.$slug'
import { Route as AdminBilletterieControleRouteImport } from './routes/admin.billetterie.controle'
import { Route as AdminBilletterieIdRouteImport } from './routes/admin.billetterie.$id'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications.$id'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaterRoute = CandidaterRouteImport.update({
  id: '/candidater',
  path: '/candidater',
  getParentRoute: () => rootRouteImport,
} as any)
const BilletterieRoute = BilletterieRouteImport.update({
  id: '/billetterie',
  path: '/billetterie',
  getParentRoute: () => rootRouteImport,
} as any)
const BilletRoute = BilletRouteImport.update({
  id: '/billet',
  path: '/billet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const BilletterieGererRoute = BilletterieGererRouteImport.update({
  id: '/billetterie_/gerer',
  path: '/billetterie/gerer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBilletterieIndexRoute = AdminBilletterieIndexRouteImport.update({
  id: '/billetterie/',
  path: '/billetterie/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesSlugRoute = AdminCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBilletterieControleRoute =
  AdminBilletterieControleRouteImport.update({
    id: '/billetterie/controle',
    path: '/billetterie/controle',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBilletterieIdRoute = AdminBilletterieIdRouteImport.update({
  id: '/billetterie/$id',
  path: '/billetterie/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/billet': typeof BilletRoute
  '/billetterie': typeof BilletterieRoute
  '/candidater': typeof CandidaterRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/temoignages': typeof TemoignagesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/billetterie/gerer': typeof BilletterieGererRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/billetterie/$id': typeof AdminBilletterieIdRoute
  '/admin/billetterie/controle': typeof AdminBilletterieControleRoute
  '/admin/categories/$slug': typeof AdminCategoriesSlugRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/billetterie/': typeof AdminBilletterieIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/billet': typeof BilletRoute
  '/billetterie': typeof BilletterieRoute
  '/candidater': typeof CandidaterRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/temoignages': typeof TemoignagesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/billetterie/gerer': typeof BilletterieGererRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/billetterie/$id': typeof AdminBilletterieIdRoute
  '/admin/billetterie/controle': typeof AdminBilletterieControleRoute
  '/admin/categories/$slug': typeof AdminCategoriesSlugRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/billetterie': typeof AdminBilletterieIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/billet': typeof BilletRoute
  '/billetterie': typeof BilletterieRoute
  '/candidater': typeof CandidaterRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/temoignages': typeof TemoignagesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/billetterie_/gerer': typeof BilletterieGererRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/billetterie/$id': typeof AdminBilletterieIdRoute
  '/admin/billetterie/controle': typeof AdminBilletterieControleRoute
  '/admin/categories/$slug': typeof AdminCategoriesSlugRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/billetterie/': typeof AdminBilletterieIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/billet'
    | '/billetterie'
    | '/candidater'
    | '/categories'
    | '/contact'
    | '/galerie'
    | '/mentions-legales'
    | '/temoignages'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/testimonials'
    | '/billetterie/gerer'
    | '/categories/$slug'
    | '/admin/'
    | '/categories/'
    | '/admin/applications/$id'
    | '/admin/billetterie/$id'
    | '/admin/billetterie/controle'
    | '/admin/categories/$slug'
    | '/admin/applications/'
    | '/admin/billetterie/'
    | '/admin/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/billet'
    | '/billetterie'
    | '/candidater'
    | '/contact'
    | '/galerie'
    | '/mentions-legales'
    | '/temoignages'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/testimonials'
    | '/billetterie/gerer'
    | '/categories/$slug'
    | '/admin'
    | '/categories'
    | '/admin/applications/$id'
    | '/admin/billetterie/$id'
    | '/admin/billetterie/controle'
    | '/admin/categories/$slug'
    | '/admin/applications'
    | '/admin/billetterie'
    | '/admin/categories'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/billet'
    | '/billetterie'
    | '/candidater'
    | '/categories'
    | '/contact'
    | '/galerie'
    | '/mentions-legales'
    | '/temoignages'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/testimonials'
    | '/billetterie_/gerer'
    | '/categories/$slug'
    | '/admin/'
    | '/categories/'
    | '/admin/applications/$id'
    | '/admin/billetterie/$id'
    | '/admin/billetterie/controle'
    | '/admin/categories/$slug'
    | '/admin/applications/'
    | '/admin/billetterie/'
    | '/admin/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  BilletRoute: typeof BilletRoute
  BilletterieRoute: typeof BilletterieRoute
  CandidaterRoute: typeof CandidaterRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalerieRoute: typeof GalerieRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  TemoignagesRoute: typeof TemoignagesRoute
  BilletterieGererRoute: typeof BilletterieGererRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidater': {
      id: '/candidater'
      path: '/candidater'
      fullPath: '/candidater'
      preLoaderRoute: typeof CandidaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billetterie': {
      id: '/billetterie'
      path: '/billetterie'
      fullPath: '/billetterie'
      preLoaderRoute: typeof BilletterieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billet': {
      id: '/billet'
      path: '/billet'
      fullPath: '/billet'
      preLoaderRoute: typeof BilletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/billetterie_/gerer': {
      id: '/billetterie_/gerer'
      path: '/billetterie/gerer'
      fullPath: '/billetterie/gerer'
      preLoaderRoute: typeof BilletterieGererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billetterie/': {
      id: '/admin/billetterie/'
      path: '/billetterie'
      fullPath: '/admin/billetterie/'
      preLoaderRoute: typeof AdminBilletterieIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/$slug': {
      id: '/admin/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/admin/categories/$slug'
      preLoaderRoute: typeof AdminCategoriesSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billetterie/controle': {
      id: '/admin/billetterie/controle'
      path: '/billetterie/controle'
      fullPath: '/admin/billetterie/controle'
      preLoaderRoute: typeof AdminBilletterieControleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billetterie/$id': {
      id: '/admin/billetterie/$id'
      path: '/billetterie/$id'
      fullPath: '/admin/billetterie/$id'
      preLoaderRoute: typeof AdminBilletterieIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminBilletterieIdRoute: typeof AdminBilletterieIdRoute
  AdminBilletterieControleRoute: typeof AdminBilletterieControleRoute
  AdminCategoriesSlugRoute: typeof AdminCategoriesSlugRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
  AdminBilletterieIndexRoute: typeof AdminBilletterieIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminBilletterieIdRoute: AdminBilletterieIdRoute,
  AdminBilletterieControleRoute: AdminBilletterieControleRoute,
  AdminCategoriesSlugRoute: AdminCategoriesSlugRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  AdminBilletterieIndexRoute: AdminBilletterieIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  BilletRoute: BilletRoute,
  BilletterieRoute: BilletterieRoute,
  CandidaterRoute: CandidaterRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  GalerieRoute: GalerieRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  TemoignagesRoute: TemoignagesRoute,
  BilletterieGererRoute: BilletterieGererRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
